import Head from 'next/head';
import { BrowserRouter } from 'react-router-dom';
import RouterOutlet from 'src/routes';
import Navbar from './components/Navbar';

const EntryPoint = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BrowserRouter>
        <Navbar />
        <RouterOutlet />
        <div className="text-4xl py-1 leading-normal">
          If you have it, footer can go here
        </div>
      </BrowserRouter>
    </>
  );
};

export default EntryPoint;
